# Generated by Django 2.2.1 on 2020-02-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.CharField(max_length=11, verbose_name='商品编号')),
                ('goods_name', models.CharField(max_length=32, verbose_name='商品名字')),
                ('goods_price', models.FloatField(verbose_name='商品价格')),
                ('goods_count', models.IntegerField(verbose_name='商品数量')),
                ('goods_location', models.CharField(max_length=32, verbose_name='商品产地')),
                ('goods_safe_date', models.IntegerField(verbose_name='商品保质期')),
                ('goods_pro_time', models.DateTimeField(auto_now=True, verbose_name='生成日期')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
