# Generated by Django 2.2.1 on 2020-02-27 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderinfo',
            table='order_info',
        ),
    ]
