# Generated by Django 2.2.1 on 2020-03-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0006_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='status',
            field=models.IntegerField(default=1, verbose_name='地址状态'),
        ),
    ]
