# Generated by Django 2.2.1 on 2020-03-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0007_useraddress_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='status',
            field=models.IntegerField(default=0, verbose_name='地址状态'),
        ),
    ]
