# Generated by Django 2.2.1 on 2020-03-10 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0008_auto_20200309_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayorderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='收货人姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='收货人手机号')),
                ('address', models.TextField(verbose_name='收货人手机号')),
                ('payorder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Buyer.PayOrder')),
            ],
        ),
    ]
