"""empty message

Revision ID: 12de2903ab9f
Revises: 506f1791b515
Create Date: 2020-03-20 10:27:52.940138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12de2903ab9f'
down_revision = '506f1791b515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date')
    # ### end Alembic commands ###
