"""empty message

Revision ID: 506f1791b515
Revises: 685b8cb1c951
Create Date: 2020-03-20 10:23:32.236400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506f1791b515'
down_revision = '685b8cb1c951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
