"""
Django settings for Demo project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
## __file__ 当前文件的路径
## abspath 绝对路径
## dirname  文件的目录
## BASE_DIR django提供的项目的根目录，方便我们使用
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
print(BASE_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
## 秘钥
SECRET_KEY = '8uv=teg9n4-v!0me34_#c-*k4yi@_4@gxw74rh4^r0sng5x(ww'

# SECURITY WARNING: don't run with debug turned on in production!
## debug 模式
## django中debug的作用：1.当代码发生改变的时候，自动重启项目。2.在客户端和控制台显示报错内容
DEBUG = True
## 允许访问的主机
ALLOWED_HOSTS = []


# Application definition
## 注册子应用
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app01',
]

# 中间件
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

##根路由的地址
ROOT_URLCONF = 'Demo.urls'

## 模板的配置
TEMPLATES = [
    {
        ## 使用的模板引擎
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  ## django的模板引擎
        # 'BACKEND': 'django.template.backends.jinja2',  ## jinja2的模板引擎 flask
        # 模板文件的目录配置  列表
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        ## APP_DIRS 设置是否在子应用中自动寻找模板内容
        ## 为True 自动从子应用中寻找模板内容
        'APP_DIRS': True,
        ## 是一些针对后端的设置
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
## django的内置服务器，使用到的wsgi的路径
WSGI_APPLICATION = 'Demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
## 数据库的配置
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
## 权限
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
## 语言
LANGUAGE_CODE = 'zh-hans'
## 时区
## 上海时区
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True
## 是否使用默认时区
# True 使用django内置的时区
# flase 使用设置的时区
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
## 静态文件的配置
## 静态文件的路由
STATIC_URL = '/static/'
#  静态文件的目录地址
STATICFILES_DIRS = (
    os.path.join(BASE_DIR,"static"),
)
