# Generated by Django 2.2.1 on 2020-02-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0005_auto_20200218_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='click',
            field=models.IntegerField(default=0, verbose_name='点击率'),
        ),
    ]
