# Generated by Django 2.2.1 on 2020-02-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0007_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
