# Generated by Django 2.2.1 on 2020-02-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_loginuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='username',
            field=models.CharField(default='', max_length=32, verbose_name='用户名'),
        ),
    ]
