# Generated by Django 2.2.1 on 2020-02-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0006_auto_20200226_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_description',
            field=models.TextField(default='good goods', verbose_name='商品的描述'),
        ),
    ]
