# Generated by Django 2.2.1 on 2020-03-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0007_goods_goods_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=32, verbose_name='用户账号')),
                ('code', models.CharField(max_length=8, verbose_name='验证码')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='验证码创建时间')),
            ],
        ),
    ]
