# Generated by Django 2.2.1 on 2020-02-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_name',
        ),
    ]
