# Generated by Django 2.2.1 on 2020-02-13 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20200213_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
