# Generated by Django 2.2.1 on 2020-02-13 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pub',
            new_name='pub_id',
        ),
    ]
