# Generated by Django 2.2.1 on 2020-02-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_person_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
